version: 0.2
env:
  parameter-store:
    DOCKER_URL: /app/docker-registery/url
    DOCKER_USERNAME: /app/docker-credential/username
    DOCKER_PASSWORD: /app/docker-credential/password
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
      - echo "login to docker"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/z1y9s0y2

  build:
    commands:
      - echo 'building image'
      - docker build -t contact_ui-frontend
      - docker tag contact_ui-frontend:latest public.ecr.aws/z1y9s0y2/contact_ui-frontend:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push contact_ui-frontend:latest public.ecr.aws/z1y9s0y2/contact_ui-frontend:latest
artifacts:
  files:
    - '**/*'
