version: 0.2
env:
  parameter-store:
    DOCKER_URL: /app/docker-registery/url
    DOCKER_USERNAME: /app/docker-credential/username
    DOCKER_PASSWORD: /app/docker-credential/password
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
      - aws --version
      - echo "login to docker"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/z1y9s0y2 	
      - REPO_URI=public.ecr.aws/z1y9s0y2/test-contact-ui
  build:
    commands:
      - echo 'building image'
      - docker build -t test-contact-ui .
      - docker tag test-contact-ui:latest public.ecr.aws/z1y9s0y2/test-contact-ui:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push public.ecr.aws/z1y9s0y2/test-contact-ui:latest
artifacts:
  files:
    - '**/*'
