version: 0.2
env:
  parameter-store:
    DOCKER_URL: /app/docker-registery/url
    DOCKER_USERNAME: /app/docker-credential/username
    DOCKER_PASSWORD: /app/docker-credential/password
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo 'login to Docker Registery'
      - aws ecr get-login-password --region ap-south-1 | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD
      - echo "build image"
      - docker build -t $DOCKER_USERNAME/contact_ui-frontend .
      - docker tag $DOCKER_USERNAME/contact_ui-frontend
      - docker push $DOCKER_USERNAME/contact_ui-frontend
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
