version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo 'login to Docker Registery'
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 470673369728.dkr.ecr.ap-south-1.amazonaws.com
      - echo "build image"
      - docker build -t frontend
      - docker tag frontend:latest 470673369728.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
      - docker push frontend:latest 470673369728.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
